### ISSUE TITLE
License to integrate in other project

### ISSUE THREAD

**Issue by perfectstrong** [daid/SliceAndDaid#2]
Good morning,
Coming from University of Technology of Troyes (France), we are in development of a new 3D-printing system, in which we use your code (this repository) to write the model processing software.
Now that our project is somewhat operational, in order to invite more people to contribute, we are going to public our software under Open Source License (which is not decided yet, but it might be dual-license allowing commercial use).
We would like your approve for using your code in our product. Contact us via laurent.daniel@utt.fr (our project leader) for more informations.
Thank you for your comprehension.

**Comment by daid** [comment]
Using this repo is the most horrible idea you ever had. It's non-functional, and only archived for history reasons. And shows a lack of research on your ends.
Please contribute to https://github.com/Ultimaker/CuraEngine, which is my actual working result, and contains years of work instead of the few days put into this repo.

I give no permission to put this this work of mine under any other license then GPLv3.

**Comment by perfectstrong** [comment]
Thank you for your reponse. We will consider to replace this module by your CuraEngine.

**Comment by perfectstrong** [comment]
Would you mind releasing this module under LGPL, please?

**Comment by daid** [comment]
Yes, I mind. Sorry. GPLv3 only.

**Comment by perfectstrong** [comment]
Thank you for your response.
